/**
 * Cached DOM bindings for the popup UI.
 *
 * Centralizing selectors keeps the rest of the popup modules focused on behavior
 * instead of repetitive `document.getElementById(...)` calls.
 */
export const dom = {
  totalCount: document.getElementById("total-count"),
  warningBox: document.getElementById("warning-box"),
  errorBox: document.getElementById("error-box"),
  fetchButton: document.getElementById("fetch-button"),
  fetchButtonLabel: document.querySelector("#fetch-button .button-label"),
  downloadButton: document.getElementById("download-button"),
  exportControl: document.getElementById("export-control"),
  exportButton: document.getElementById("export-button"),
  exportButtonLabel: document.getElementById("export-button-label"),
  exportMenuButton: document.getElementById("export-menu-button"),
  exportMenu: document.getElementById("export-menu"),
  get exportMenuOptions() {
    return [...document.querySelectorAll("[data-export-type]")];
  },
  selectAllButton: document.getElementById("select-all-button"),
  clearSelectionButton: document.getElementById("clear-selection-button"),
  summaryPanel: document.querySelector(".summary-panel"),
  pickerPanelLabel: document.getElementById("picker-panel-label"),
  selectionSummary: document.getElementById("selection-summary"),
  creatorResultsTabs: document.getElementById("creator-results-tabs"),
  fetchProgressPanel: document.getElementById("fetch-progress-panel"),
  fetchProgressActions: document.getElementById("fetch-progress-actions"),
  fetchProgressStage: document.getElementById("fetch-progress-stage"),
  fetchProgressDetail: document.getElementById("fetch-progress-detail"),
  fetchProgressPercent: document.getElementById("fetch-progress-percent"),
  fetchProgressFill: document.getElementById("fetch-progress-fill"),
  fetchProgressPauseAction: document.getElementById("fetch-progress-pause-action"),
  fetchProgressAction: document.getElementById("fetch-progress-action"),
  fetchProgressSource: document.getElementById("fetch-progress-source"),
  fetchProgressCount: document.getElementById("fetch-progress-count"),
  fetchProgressEta: document.getElementById("fetch-progress-eta"),
  characterSelectionGrid: document.getElementById("character-selection-grid"),
  emptyState: document.getElementById("empty-state"),
  emptyStateImage: document.querySelector(".empty-state-image"),
  emptyStateText: document.getElementById("empty-state-text"),
  itemsList: document.getElementById("items-list"),
  pickerScrollRegion: document.getElementById("picker-scroll-region"),
  pickerPanel: document.querySelector(".picker-panel"),
  pickerToolbar: document.querySelector(".picker-toolbar"),
  controlsPanel: document.querySelector(".controls-panel"),
  searchInput: document.getElementById("search-input"),
  sourceSelectField: document.querySelector(".source-select-field"),
  sourceSelectControl: document.getElementById("source-select-control"),
  sourceSelectButton: document.getElementById("source-select-button"),
  sourceSelectLabel: document.getElementById("source-select-label"),
  sourceSelectMenu: document.getElementById("source-select-menu"),
  sourceSelectInputs: [...document.querySelectorAll('input[data-source-group="overview"]')],
  characterSelectField: document.getElementById("character-select-field"),
  characterSelectControl: document.getElementById("character-select-control"),
  characterSelectButton: document.getElementById("character-select-button"),
  characterSelectLabel: document.getElementById("character-select-label"),
  characterSelectMenu: document.getElementById("character-select-menu"),
  get characterSelectInputs() {
    return [...document.querySelectorAll('input[data-source-group="characters"]')];
  },
  sortSelect: document.getElementById("sort-select"),
  runForm: document.getElementById("run-form"),
  appShell: document.querySelector(".app"),
  appVersionLabel: document.getElementById("app-version-label"),
  backToTopButton: document.getElementById("back-to-top-button"),
  downloadOverlay: document.getElementById("download-overlay"),
  downloadOverlayTitle: document.getElementById("download-overlay-title"),
  downloadOverlayStatus: document.getElementById("download-overlay-status"),
  downloadOverlayCount: document.getElementById("download-overlay-count"),
  downloadOverlayPercent: document.getElementById("download-overlay-percent"),
  downloadOverlayFill: document.getElementById("download-overlay-fill"),
  downloadOverlayThanks: document.getElementById("download-overlay-thanks"),
  downloadOverlayCancel: document.getElementById("download-overlay-cancel"),
  tabButtons: [...document.querySelectorAll(".tab-button")],
  tabPanels: [...document.querySelectorAll(".tab-panel")],
  maxVideosInput: document.getElementById("max-videos-input"),
  defaultSourceControl: document.getElementById("default-source-control"),
  defaultSourceButton: document.getElementById("default-source-button"),
  defaultSourceLabel: document.getElementById("default-source-label"),
  defaultSourceMenu: document.getElementById("default-source-menu"),
  defaultSourceInputs: [...document.querySelectorAll('input[data-source-group="settings"]')],
  defaultSortInput: document.getElementById("default-sort-input"),
  defaultThemeInput: document.getElementById("default-theme-input"),
  clearStorageButton: document.getElementById("clear-storage-button"),
  settingsStatus: document.getElementById("settings-status"),
  themeToggle: document.getElementById("theme-toggle"),
  creatorDialog: document.getElementById("creator-dialog"),
  creatorDialogForm: document.getElementById("creator-dialog-form"),
  creatorDialogInput: document.getElementById("creator-dialog-input"),
  creatorDialogError: document.getElementById("creator-dialog-error"),
  creatorDialogCancel: document.getElementById("creator-dialog-cancel"),
  creatorDialogSubmit: document.getElementById("creator-dialog-submit"),
  creatorDetailsDialog: document.getElementById("creator-details-dialog"),
  creatorDetailsClose: document.getElementById("creator-details-close"),
  creatorDetailsTitle: document.getElementById("creator-details-title"),
  creatorDetailsSummary: document.getElementById("creator-details-summary"),
  creatorDetailsProfile: document.getElementById("creator-details-profile"),
  creatorDetailsStats: document.getElementById("creator-details-stats"),
  creatorDetailsPreferences: document.getElementById("creator-details-preferences"),
  creatorDetailsCode: document.getElementById("creator-details-code"),
};
