/**
 * Mutable popup-only state.
 *
 * The background worker remains the source of truth for scan and download data.
 * This module only tracks transient UI concerns that belong to the popup itself.
 */
export const popupState = {
  titleSaveTimers: new Map(),
  pollTimer: null,
  settingsSaveTimer: null,
  fetchStatusTimer: null,
  fetchDrawerExpanded: false,
  fetchDrawerUserToggled: false,
  isFullscreenView: false,
  activeTab: "overview",
  activeFetchStatusMessage: "",
  lastRenderedSignature: "",
  lastSelectionScreenSignature: "",
  latestBusy: false,
  latestPaused: false,
  characterAccountsLoading: false,
  hasAttemptedCharacterAccountLoad: false,
  characterAccounts: [],
  selectedCharacterAccountIds: [],
  creatorProfiles: [],
  selectedCreatorProfileIds: [],
  activeSourceSelectionTab: "",
  activeCreatorResultsTab: "all",
  preferredExportType: "prompts",
  exportMenuOpen: false,
  openCreatorActionMenuId: "",
  creatorDetailsProfileId: "",
  creatorDetailsHeroSignature: "",
  creatorPreferenceSavingProfileId: "",
  creatorDialogSubmitting: false,
  currentPhase: "idle",
  updateGateHidden: false,
  skippedUpdateVersion: "",
  latestUpdateStatus: {
    phase: "checking",
    currentVersion: "",
    latestVersion: "",
    latestGitHubVersion: "",
    latestManifestDetected: false,
    latestZipDetected: false,
    message: "",
    detail: "",
    progress: 0,
    lastCheckedAt: null,
    installFolderLinked: false,
    automaticUpdatesEnabled: true,
    updateAvailable: false,
    pendingUpdateVersion: "",
    pendingDeferred: false,
    pendingUpdateReady: false,
    changelogMarkdown: "",
    error: "",
  },
  hasCustomOverviewSourceSelection: false,
  pendingDownloadStart: false,
  downloadOverlaySessionActive: false,
  appliedSettingsDefaults: {
    source: "",
    sort: "",
  },
  latestRenderState: {
    items: [],
    selectedKeys: [],
    titleOverrides: {},
    totalCount: 0,
    selectedCountTotal: 0,
    disableInputs: false,
    phase: "idle",
  },
  latestRuntimeState: null,
  browseState: {
    query: "",
    sort: "newest",
  },
  latestSummaryContext: {
    totalCount: 0,
    selectedCount: 0,
    visibleCount: 0,
    visibleSelectedCount: 0,
    phase: "idle",
  },
  downloadModeAutoChecked: false,
};
