/**
 * Mutable popup-only state.
 *
 * The background worker remains the source of truth for scan and download data.
 * This module only tracks transient UI concerns that belong to the popup itself.
 */
export const popupState = {
  pollTimer: null,
  settingsSaveTimer: null,
  fetchStatusTimer: null,
  fetchDrawerExpanded: false,
  fetchDrawerHoverExpanded: false,
  fetchDrawerUserToggled: false,
  isFullscreenView: false,
  activeTab: "overview",
  activeFetchStatusMessage: "",
  lastRenderedSignature: "",
  lastSelectionScreenSignature: "",
  latestBusy: false,
  latestPaused: false,
  characterAccountsLoading: false,
  hasAttemptedCharacterAccountLoad: false,
  characterAccounts: [],
  selectedCharacterAccountIds: [],
  creatorProfiles: [],
  selectedCreatorProfileIds: [],
  activeSourceSelectionTab: "",
  activeCreatorResultsTab: "all",
  preferredExportType: "prompts",
  exportMenuOpen: false,
  openCreatorActionMenuId: "",
  creatorDetailsProfileId: "",
  creatorDetailsHeroSignature: "",
  creatorPreferenceSavingProfileId: "",
  creatorDialogSubmitting: false,
  titleDialogItemKey: "",
  titleDialogDefaultTitle: "",
  titleDialogInitialTitle: "",
  pendingScopedSelectionSave: null,
  currentPhase: "idle",
  startupGateLocked: true,
  updateGateHidden: false,
  restoreGatePhase: "idle",
  restoreGateVisible: false,
  skippedUpdateVersion: "",
  latestUpdateStatus: {
    phase: "checking",
    currentVersion: "",
    latestVersion: "",
    latestGitHubVersion: "",
    latestManifestDetected: false,
    latestZipDetected: false,
    message: "",
    detail: "",
    progress: 0,
    lastCheckedAt: null,
    installFolderLinked: false,
    automaticUpdatesEnabled: true,
    updateAvailable: false,
    pendingUpdateVersion: "",
    pendingDeferred: false,
    pendingUpdateReady: false,
    changelogMarkdown: "",
    error: "",
  },
  hasCustomOverviewSourceSelection: false,
  pendingDownloadStart: false,
  downloadOverlaySessionActive: false,
  appliedSettingsDefaults: {
    source: "",
    sort: "",
    viewMode: "list",
  },
  latestRenderState: {
    items: [],
    selectedKeys: [],
    titleOverrides: {},
    totalCount: 0,
    selectedCountTotal: 0,
    disableInputs: false,
    phase: "idle",
  },
  latestRuntimeState: null,
  browseState: {
    query: "",
    sort: "newest",
    viewMode: "list",
  },
  latestSummaryContext: {
    totalCount: 0,
    selectedCount: 0,
    visibleCount: 0,
    visibleSelectedCount: 0,
    phase: "idle",
  },
  virtualList: {
    disableInputs: false,
    phase: "idle",
    sort: "newest",
    query: "",
    activeCreatorResultsTab: "all",
    viewMode: "list",
    creatorTabsSignature: "",
    filteredItems: [],
    visibleCount: 0,
    visibleSelectedCount: 0,
    renderedItemsByKey: new Map(),
    rangeStart: 0,
    rangeEnd: 0,
    listRowHeight: 214,
    gridColumns: 1,
    gridCardWidth: 160,
    gridRowHeight: 284,
    lastViewportWidth: 0,
    lastViewportHeight: 0,
    lastScrollTop: -1,
    lastPaddingTop: 0,
    lastPaddingBottom: 0,
    lastWindowSignature: "",
    scrollFrame: 0,
    measureFrame: 0,
    tooltipItemKey: "",
    tooltipHideTimer: 0,
  },
};
